Emails sent in a loop, ERROR in log
Trying what the doc says.

Log says:
INFO: SELECT endpoint_email_subscriptions.account_id, endpoint_email_subscriptions.user_id, endpoint_email_subscriptions.event_type
FROM endpoint_email_subscriptions
WHERE endpoint_email_subscriptions.account_id = $1 AND endpoint_email_subscriptions.event_type = $2
INFO: ('901578', 'policies-instant-mail')
ERROR: Received error while trying to send email: Illegal in managed mode, use `raise_commit` instead.
INFO: Rolling back the Kafka seek position after 10 second sleep
INFO: INSERT INTO email_aggregation (account_id, insight_id, created, payload) VALUES ($1, $2, now(), $3) RETURNING email_aggregation.id, email_aggregation.account_id, email_aggregation.insight_id, email_aggregation.created, email_aggregation.payload
INFO: ('901578', 'd4039530-4e3c-44d8-83b9-44de55400c2b', '"{\\"tenantId\\": \\"901578\\", \\"insightId\\": \\"d4039530-4e3c-44d8-83b9-44de55400c2b\\", \\"tags\\": {\\"display_name\\": \\"Thomas RHEL8 VM\\"}, ... (215 characters truncated) ... ot installed on any systems test\\", \\"Test policy that triggers every single time\\", \\"Facts.arch policy\\", \\"Ensure fapolicyd is enabled\\"]}"')
INFO: COMMIT
INFO: Params: {'tenantId': '901578', 'insightId': 'd4039530-4e3c-44d8-83b9-44de55400c2b', 'tags': {'display_name': 'Thomas RHEL8 VM'}, 'triggerNames': ['Ensure openscap is installed', 'Ensure usbguard is enabled', 'Ensure firewalld is enabled', 'Ensure all systems are updated to latest RHEL8.1 release', 'Ensure wireshark is not installed on any systems test', 'Test policy that triggers every single time', 'Facts.arch policy', 'Ensure fapolicyd is enabled']}
INFO: SELECT endpoint_email_subscriptions.account_id, endpoint_email_subscriptions.user_id, endpoint_email_subscriptions.event_type
FROM endpoint_email_subscriptions